name: flutter-ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    name: Unit tests on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
                - uses: actions/setup-java@v1
                with:
                  java-version: '17.x'
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed --dry-run .
      - run: flutter test
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk